networks:
  vlan_ansible:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.0.0/16

  vlan_serveurs:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.1.0/24

  vlan_postes:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.2.0/24

  vlan_DMZ:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.3.0/24

  admin:
    driver: bridge

  internet:
    driver: bridge

services:
  ansible:
    build: ./docker-images/ansible-serveur
    hostname: ansible
    cap_add:
      - NET_ADMIN
    networks:
      admin: {}
      vlan_ansible:
        ipv4_address: 10.1.255.254
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
      - ./docker-volumes/ansible:/home/ansible/ansible
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "tail -f /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 3

  virtual1:
    build: ./docker-images/debian-serveur
    hostname: virtual1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    networks:
      vlan_ansible:
        ipv4_address: 10.1.1.10
      vlan_serveurs:
        ipv4_address: 10.0.1.10
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
    depends_on:
      ansible:
        condition: service_healthy

  virtual2:
    build: ./docker-images/debian-serveur
    hostname: virtual2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    networks:
      vlan_ansible:
        ipv4_address: 10.1.1.11
      vlan_serveurs:
        ipv4_address: 10.0.1.11
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
    depends_on:
      ansible:
        condition: service_healthy

  pc1:
    build: ./docker-images/debian-serveur
    hostname: pc1
    networks:
      vlan_ansible:
        ipv4_address: 10.1.2.10
      vlan_postes:
        ipv4_address: 10.0.2.10
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
    depends_on:
      ansible:
        condition: service_healthy

  pc2:
    build: ./docker-images/debian-serveur
    hostname: pc2
    networks:
      vlan_ansible:
        ipv4_address: 10.1.2.11
      vlan_postes:
        ipv4_address: 10.0.2.11
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
    depends_on:
      ansible:
        condition: service_healthy

  virtualdmz1:
    build: ./docker-images/debian-serveur
    hostname: virtualdmz1
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    networks:
      vlan_ansible:
        ipv4_address: 10.1.3.10
      vlan_DMZ:
        ipv4_address: 10.0.3.10
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
    depends_on:
      ansible:
        condition: service_healthy

  routeur:
    build: ./docker-images/debian-serveur
    hostname: routeur
    privileged: true
    networks:
      vlan_ansible:
        ipv4_address: 10.1.0.254
      vlan_serveurs:
        ipv4_address: 10.0.1.254
      vlan_postes:
        ipv4_address: 10.0.2.254
      vlan_DMZ:
        ipv4_address: 10.0.3.254
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
    depends_on:
      ansible:
        condition: service_healthy

