networks:
  vlan_ansible:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.0.0/16
  vlan_lambda:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet 10.2.0.0/16
  admin:
    driver: bridge

  internet:
    driver: bridge


services:
  ansible:
    build: ./docker-images/ansible-serveur
    networks:
      admin: {}
      vlan_ansible:
        ipv4_address: 10.1.255.254
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
      - ./docker-volumes/ansible:/home/ansible/ansible

  virtual1:
    build: ./docker-images/alpine-serveur
    networks:
      vlan_ansible:
        ipv4_address: 10.1.2.10
      vlan_lambda:
        ipv4_adress: 10.2.2.10
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh

  virtual2:
    build: ./docker-images/alpine-serveur
    networks:
      vlan_ansible:
        ipv4_address: 10.1.2.11
      vlan_lambda:
        ipv4_address: 10.2.2.11
    volumes:
      - ./docker-volumes/tmp:/tmp/ssh
