---
- name: Install DVWA on virtualdmz1
  hosts: dmz
  become: true
  become_method: sudo
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - php
          - php-mysqli
          - php-gd
          - libapache2-mod-php
          - curl
          - git
          - mariadb-client
        state: present
        update_cache: yes

    - name: Enable and start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Clone DVWA from GitHub
      git:
        repo: 'https://github.com/digininja/DVWA.git'
        dest: /var/www/html/DVWA
        version: HEAD

    - name: Set ownership for DVWA files
      file:
        path: /var/www/html/DVWA
        owner: www-data
        group: www-data
        recurse: yes

    - name: Copy DVWA config file
      copy:
        src: /var/www/html/DVWA/config/config.inc.php.dist
        dest: /var/www/html/DVWA/config/config.inc.php
        remote_src: yes

- name: Set allow_url_include to On in php.ini
  hosts: dmz
  become: true
  become_method: sudo
  tasks:
    - name: Update allow_url_include in php.ini
      lineinfile:
        path: "/etc/php/8.2/apache2/php.ini"
        regexp: '^allow_url_include\s*='
        line: 'allow_url_include = On'
        backrefs: yes

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
