---
- name: Install DVWA on virtualdmz1
  hosts: dmz
  become: true
  become_method: sudo
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - php
          - php-mysqli
          - php-gd
          - libapache2-mod-php
          - curl
          - git
          - mariadb-client
        state: present
        update_cache: yes

    - name: Enable and start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Clone DVWA from GitHub
      git:
        repo: 'https://github.com/digininja/DVWA.git'
        dest: /var/www/html/DVWA
        version: HEAD

    - name: Set ownership for DVWA files
      file:
        path: /var/www/html/DVWA
        owner: www-data
        group: www-data
        recurse: yes

    - name: Copy DVWA config file
      copy:
        src: /var/www/html/DVWA/config/config.inc.php.dist
        dest: /var/www/html/DVWA/config/config.inc.php
        remote_src: yes

- name: Update config.inc.php for DVWA database connection
  hosts: dmz
  become: true
  become_method: sudo
  tasks:
    - name: Update DB_SERVER in config.inc.php
      command: >
        sed -i "s/$_DVWA\[\s*\'db_server\'\s*\]\s*=\s*\'[^\']*\'/$_DVWA[\'db_server\'] = getenv(\'DB_SERVER\') ?: \'10.0.1.10\';/" /var/www/html/DVWA/config/config.inc.php

    - name: Update DB_DATABASE in config.inc.php
      command: >
        sed -i "s/$_DVWA\[\s*\'db_database\'\s*\]\s*=\s*\'[^\']*\'/$_DVWA[\'db_database\'] = getenv(\'DB_DATABASE\') ?: \'dvwa_db\';/" /var/www/html/DVWA/config/config.inc.php

    - name: Update DB_USER in config.inc.php
      command: >
        sed -i "s/$_DVWA\[\s*\'db_user\'\s*\]\s*=\s*\'[^\']*\'/$_DVWA[\'db_user\'] = getenv(\'DB_USER\') ?: \'dvwa\';/" /var/www/html/DVWA/config/config.inc.php

    - name: Update DB_PASSWORD in config.inc.php
      command: >
        sed -i "s/$_DVWA\[\s*\'db_password\'\s*\]\s*=\s*\'[^\']*\'/$_DVWA[\'db_password\'] = getenv(\'DB_PASSWORD\') ?: \'azerty\';/" /var/www/html/DVWA/config/config.inc.php

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
