---
- name: Install DVWA on virtualdmz1
  hosts: dmz
  become: true
  become_method: sudo
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - php
          - php-mysqli
          - php-gd
          - libapache2-mod-php
          - curl
          - git
          - mariadb-client
        state: present
        update_cache: yes

    - name: Enable and start Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Clone DVWA from GitHub
      git:
        repo: 'https://github.com/digininja/DVWA.git'
        dest: /var/www/html/DVWA
        version: HEAD

    - name: Set ownership for DVWA files
      file:
        path: /var/www/html/DVWA
        owner: www-data
        group: www-data
        recurse: yes

    - name: Copy DVWA config file
      copy:
        src: /var/www/html/DVWA/config/config.inc.php.dist
        dest: /var/www/html/DVWA/config/config.inc.php
        remote_src: yes

- name: Update DVWA config for remote database
  hosts: dmz
  become: true
  become_method: sudo
  tasks:
    - name: Update DVWA config for remote database
      lineinfile:
        path: /var/www/html/DVWA/config/config.inc.php
        regexp: "^(\\$DB_HOST\\s*=).*;"
        line: "\\1 '10.0.1.10';"
        backrefs: yes
      notify: Restart Apache

    - name: Update DVWA config for database name
      lineinfile:
        path: /var/www/html/DVWA/config/config.inc.php
        regexp: "^(\\$DB_DATABASE\\s*=).*;"
        line: "\\1 'dvwa_db';"
        backrefs: yes

    - name: Update DVWA config for database user
      lineinfile:
        path: /var/www/html/DVWA/config/config.inc.php
        regexp: "^(\\$DB_USER\\s*=).*;"
        line: "\\1 'dvwa';"
        backrefs: yes

    - name: Update DVWA config for database password
      lineinfile:
        path: /var/www/html/DVWA/config/config.inc.php
        regexp: "^(\\$DB_PASSWORD\\s*=).*;"
        line: "\\1 'azerty';"
        backrefs: yes

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
