---
- name: Configure default gateway on virutal1
  hosts: 10.1.1.10
  become: True
  become_method: sudo

  tasks:
   - name: create_file_interfaces
     file:
       path: /etc/systemd/network/interfaces
       state: touch

   - name: Set_default_gateway_using_block
     blockinfile:
       path: /etc/systemd/network/interfaces
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
       block: |
         #Interfaces configuration
         auto lo
         iface lo inet loopback

         auto eth0
         iface eth0 inet static
                 address 10.0.1.10
                 gateway 10.0.1.254
         auto eth1
         iface eth1 inet static
                 address 10.1.1.10
                 gateway 10.1.255.254

   - name: command restart networking
     command: sudo systemctl restart systemd-networkd

- name: Configure default gateway on virtual2
  hosts: 10.1.1.11
  become: True
  become_method: sudo

  tasks:
   - name: create_file_interfaces
     file:
       path: /etc/systemd/network/interfaces
       state: touch

   - name: Set_default_gateway_using_block
     blockinfile:
       path: /etc/systemd/network/interfaces
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
       block: |
         #Interfaces configuration
         auto lo
         iface lo inet loopback

         auto eth0
         iface eth0 inet static
                 address 10.0.1.11
                 gateway 10.0.1.254
         auto eth1
         iface eth1 inet static
                 address 10.1.1.11
                 gateway 10.1.255.254

   - name: command restart networking
     command: sudo systemctl restart systemd-networkd

- name: Configure default gateway on pc1
  hosts: 10.1.2.10
  become: True
  become_method: sudo

  tasks:
   - name: create_file_interfaces
     file:
       path: /etc/systemd/network/interfaces
       state: touch

   - name: Set_default_gateway_using_block
     blockinfile:
       path: /etc/systemd/network/interfaces
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
       block: |
         #Interfaces configuration
         auto lo
         iface lo inet loopback

         auto eth0
         iface eth0 inet static
                 address 10.0.2.10
                 gateway 10.0.2.254
         auto eth1
         iface eth1 inet static
                 address 10.1.2.10
                 gateway 10.1.255.254

   - name: command restart networking
     command: sudo systemctl restart systemd-networkd

- name: Configure default gateway on pc2
  hosts: 10.1.2.11
  become: True
  become_method: sudo

  tasks:
   - name: create_file_interfaces
     file:
       path: /etc/systemd/network/interfaces
       state: touch

   - name: Set_default_gateway_using_block
     blockinfile:
       path: /etc/systemd/network/interfaces
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
       block: |
         #Interfaces configuration
         auto lo
         iface lo inet loopback

         auto eth0
         iface eth0 inet static
                 address 10.0.2.11
                 gateway 10.0.2.254
         auto eth1
         iface eth1 inet static
                 address 10.1.2.10
                 gateway 10.1.255.254

   - name: command restart networking
     command: sudo systemctl restart systemd-networkd


- name: Configure default gateway on DMZ1
  hosts: 10.1.3.10
  become: True
  become_method: sudo

  tasks:
   - name: create_file_interfaces
     file:
       path: /etc/systemd/network/interfaces
       state: touch

   - name: Set_default_gateway_using_block
     blockinfile:
       path: /etc/systemd/network/interfaces
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
       block: |
         #Interfaces configuration
         auto lo
         iface lo inet loopback

         auto eth0
         iface eth0 inet static
                 address 10.0.3.10
                 gateway 10.0.3.254
         auto eth1
         iface eth1 inet static
                 address 10.1.3.10
                 gateway 10.1.255.254

   - name: command restart networking
     command: sudo systemctl restart systemd-networkd
