---
 -      name: Configure default gateway on Alpine Linux
	hosts: all
	become: True
	become_method: sudo
	tasks:
	-  name: Set default gateway using ip route command
	   ansible.builtin.command: 
             cmd: ip route add default via {{10.2.2.254}}
           when: gateway_ip is defined

        -  name: Ensure default gateway is set correctly
           ansible.builtin.shell: ip route show default
           register: route_output

        -  name: Display current default gateway
           debug:
           var: route_output.stdout
