---
- name: Configure default gateway on Alpine Linux
  hosts: 10.1.1.10
  become: True
  become_method: sudo

  tasks:
   - name: create_file_interfaces
     file:
       path: /etc/network/interfaces
       state: touch

   - name: Set_default_gateway_using_block
     blockinfile:
       path: /etc/network/interfaces
       marker: "# {mark} ANSIBLE MANAGED BLOCK"
       block: |
         #Interfaces configuration
         auto lo
         iface lo inet loopback

         auto eth0
         iface eth0 inet static
                 address 10.1.1.10
                 gateway 10.1.1.254
         auto eth1
         iface eth1 inet static
                 address 10.0.1.10
                 gateway 10.0.1.254

   - name: command restart networking
     command: sudo rc-service networking restart
