---
- name: Configure default gateway on Alpine Linux
  hosts: serveurs
  become: True
  become_method: sudo

  tasks:
    -  name: Set_default_gateway_using_ip_route_command
       ansible.builtin.command:
         cmd: ip route add default via {{10.2.2.254}}
