- name: Configure default gateway on serveur
  hosts: lan
  become: True
  become_method: sudo

  tasks:
    - name: Enable systemd-networkd service
      systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Restart systemd-networkd to apply changes
      command: ip route add default via 10.0.1.254

- name: Configure default gateway on postes
  hosts: clients
  become: True
  become_method: sudo

  tasks:
    - name: Enable systemd-networkd service
      systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Restart systemd-networkd to apply changes
      command: ip route add default via 10.0.2.254

- name: Configure default gateway on dmz
  hosts: dmz
  become: True
  become_method: sudo

  tasks:
    - name: Enable systemd-networkd service
      systemd:
        name: systemd-networkd
        enabled: yes
        state: started

    - name: Restart systemd-networkd to apply changes
      command: ip route add default via 10.0.3.254
