networks:
  vlan_ansible:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.0.0/16

  admin:
    driver: bridge

  internet:
    driver: bridge


services:
  ansible:
    build: ansible
    networks:
      admin: {}
      vlan_ansible:
        ipv4_address: 10.1.255.254
    volumes:
      - ./tmp:/tmp/ssh:ansible

  virtual1:
    build: serveur-alpine
    networks:
      vlan_ansible:
        ipv4_address: 10.1.2.10
    volumes:
      - ./tmp:/tmp/ssh:ansible

#  virtual2:
#    build: serveur-alpine
#    networks:
#      vlan_ansible:
#        ipv4_address: 10.1.2.11
#    cap_add:
#      - NET_ADMIN
#    command: |
#      /bin/sh -c "
#      tail -f /dev/null
#      "

